animations {
  enabled = false
  animation = fade, 0
}

input-field {
  size = 650, 100
  font_family = CaskaydiaCove Nerd Font
  placeholder_text = <span> Enter Password 󰈷 </span>
  fail_text = <i>$FAIL ($ATTEMPTS)</i>
  font_color = rgb(255,255,255)
  outer_color= rgb(0,0,0)
  inner_color = rgb(0,0,0)
  fade_on_empty = false
  outline_thickness = 4
  dots_text_format = *
  dots_size = .4
}

auth {
  fingerprint:enabled = true
}
